// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from kd-message.proto

package com.github.kd;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class KDMessage implements Externalizable, Message<KDMessage>, Schema<KDMessage>
{
    public enum MessageType implements com.dyuproject.protostuff.EnumLite<MessageType>
    {
        REQUEST(0),
        REPLY(1);
        
        public final int number;
        
        private MessageType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static MessageType valueOf(int number)
        {
            switch(number) 
            {
                case 0: return REQUEST;
                case 1: return REPLY;
                default: return null;
            }
        }
    }


    public static Schema<KDMessage> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static KDMessage getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final KDMessage DEFAULT_INSTANCE = new KDMessage();

    
    private MessageType type;

    public KDMessage()
    {
        
    }

    public KDMessage(
        MessageType type
    )
    {
        this.type = type;
    }

    // getters and setters

    // type

    public MessageType getType()
    {
        return type;
    }

    public void setType(MessageType type)
    {
        this.type = type;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<KDMessage> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public KDMessage newMessage()
    {
        return new KDMessage();
    }

    public Class<KDMessage> typeClass()
    {
        return KDMessage.class;
    }

    public String messageName()
    {
        return KDMessage.class.getSimpleName();
    }

    public String messageFullName()
    {
        return KDMessage.class.getName();
    }

    public boolean isInitialized(KDMessage message)
    {
        return 
            message.type != null;
    }

    public void mergeFrom(Input input, KDMessage message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.type = MessageType.valueOf(input.readEnum());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, KDMessage message) throws IOException
    {
        if(message.type == null)
            throw new UninitializedMessageException(message);
        output.writeEnum(1, message.type.number, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
